#ifndef HARDWARE_CONFIG_H
#define HARDWARE_CONFIG_H

#include <libopencm3/stm32/gpio.h>

#define STM32_MIDI_SYSTEM_CORE_CLOCK_HZ 72000000u

#define STM32_MIDI_USB_D_MINUS_PIN GPIO11
#define STM32_MIDI_USB_D_PLUS_PIN GPIO12

#define STM32_MIDI_ROW_SELECT_PIN_MASK (GPIO0 | GPIO1 | GPIO11)
#define STM32_MIDI_ROW_SELECT_COUNT 3u
#define STM32_MIDI_MUX_SELECT_PA_PIN_MASK (GPIO1 | GPIO2)
#define STM32_MIDI_MUX_SELECT_PB_PIN GPIO12
#define STM32_MIDI_MUX_OUTPUT_PIN GPIO13

#define STM32_MIDI_USB_MIDI_EP_IN 0x81u
#define STM32_MIDI_USB_MIDI_EP_SIZE 64u

#endif
